import type { Lesson, Mission } from "@/lib/types";

export const demoLessons: Lesson[] = [
  {
    id: "needs-and-wants",
    slug: "needs-and-wants",
    title: "Needs and wants",
    summary: "A need helps you stay well. A want is nice to have.",
    body: "A need is something that helps you stay healthy, safe, or ready to learn. Food, water, a way to get where you must go, and school supplies are often needs. A want is something fun or extra, like stickers, a toy, or a fancy snack. Wants are allowed. The skill is noticing which is which before you spend. In MoneyVerse every coin is a pretend game coin.",
    topic: "Needs vs wants",
    ageMin: 8,
    ageMax: 12,
    order: 1,
  },
  {
    id: "opportunity-cost",
    slug: "opportunity-cost",
    title: "Opportunity cost",
    summary: "Choosing one thing means letting another go.",
    body: "Opportunity cost is what you give up when you choose. If you spend 8 game coins on cookies, those same coins cannot also buy a bus ride. That does not make the cookies a mistake. It means every spend has a trade-off. Naming the trade-off helps you decide on purpose.",
    topic: "Opportunity cost",
    ageMin: 8,
    ageMax: 12,
    order: 2,
  },
  {
    id: "saving-and-interest",
    slug: "saving-and-interest",
    title: "Saving goals and simple interest",
    summary: "A goal tells savings where to go. Interest is a small extra.",
    body: "A savings goal has a name and an amount, like a bicycle for 150 game coins. A budget is a plan for how coins will be used. Income is coins that come in, such as helper pay. If you leave game coins in the jar, this town's bank adds a small bonus. That bonus is a simple-interest example: extra coins for keeping savings put. Real banks and investments follow different rules, and investing can lose money. MoneyVerse is practice with fictional coins, not personal financial advice.",
    topic: "Saving",
    ageMin: 8,
    ageMax: 12,
    order: 3,
  },
  {
    id: "profit",
    slug: "profit",
    title: "Revenue, expenses, and profit",
    summary: "Profit is what is left after costs.",
    body: "Revenue is the coins customers pay you. For a lemonade stand, revenue = cups sold × price. Expenses are the costs you pay to run the stand, such as lemons, sugar, and cups. Profit = revenue − expenses. If the number is below zero, it is a loss. A loss means the plan cost more than it brought in. Changing the price or the supply batch changes both sides of the formula. Customers in this game follow a set rule so you can compare choices.",
    topic: "Profit",
    ageMin: 8,
    ageMax: 12,
    order: 4,
  },
];

export const demoMissions: Mission[] = [
  {
    id: "needs-vs-wants",
    slug: "needs-vs-wants",
    title: "Needs vs Wants",
    summary: "Spend a 24-coin outing budget and notice trade-offs.",
    story:
      "Pip is going to the park. The budget for the whole outing is 24 fictional game coins. Some things help Pip stay fed, safe, and ready to play. Other things are fun extras. Every choice leaves a different pile of coins for later.",
    learningGoal: "Tell a need from a want, and name the opportunity cost of a choice.",
    ageMin: 8,
    ageMax: 12,
    difficulty: "easy",
    topic: "Needs vs wants",
    order: 1,
    engine: "choices",
    startingCoins: 24,
    goalAmount: null,
    needsRequired: 2,
    successHeadline: "You looked after the day and the budget.",
    practiceHeadline: "You practiced the difference. Replay to cover more needs.",
    steps: [
      {
        id: "breakfast",
        title: "Before the park",
        prompt: "Pip's tummy is rumbling. The outing has not started, and the budget is still 24 game coins.",
        income: 0,
        incomeLabel: "",
        choices: [
          {
            id: "apple",
            label: "Eat the apple from home",
            detail: "A need. It costs 0 game coins and gives Pip energy.",
            coinDelta: 0,
            bonusCoins: 0,
            tag: "need",
            meetsNeed: true,
            feedbackTitle: "Food is a need",
            feedbackBody:
              "The apple helps Pip's body. That makes it a need. It also costs nothing, so the whole budget stays ready for later.",
          },
          {
            id: "cookies",
            label: "Buy a tall stack of cookies",
            detail: "A want. Tasty, and it costs 8 game coins.",
            coinDelta: -8,
            bonusCoins: 0,
            tag: "want",
            meetsNeed: false,
            feedbackTitle: "Cookies are a want",
            feedbackBody:
              "Cookies can be fun. They are a want, not a need. The opportunity cost is 8 game coins that cannot also pay for the bus or water.",
          },
          {
            id: "skip-food",
            label: "Skip food for now",
            detail: "Costs 0, but Pip stays hungry.",
            coinDelta: 0,
            bonusCoins: 0,
            tag: "spend",
            meetsNeed: false,
            feedbackTitle: "Hunger is a need",
            feedbackBody:
              "Saving coins matters, and so does eating. Skipping food leaves a need unmet. This is practice, and a replay can try the apple.",
          },
        ],
      },
      {
        id: "travel",
        title: "Getting there",
        prompt: "Clouds roll in. Pip still needs to reach the park.",
        income: 0,
        incomeLabel: "",
        choices: [
          {
            id: "bus",
            label: "Pay the bus fare",
            detail: "A need today. The fare is 5 game coins.",
            coinDelta: -5,
            bonusCoins: 0,
            tag: "need",
            meetsNeed: true,
            feedbackTitle: "The fare covers the trip",
            feedbackBody:
              "The bus gets Pip to the park in the rain. Spending 5 game coins on that need is a plan, not a slip-up.",
          },
          {
            id: "walk",
            label: "Walk in a borrowed coat",
            detail: "A neighbor shares a spare coat. The walk costs 0.",
            coinDelta: 0,
            bonusCoins: 0,
            tag: "need",
            meetsNeed: true,
            feedbackTitle: "The need is covered for free",
            feedbackBody:
              "Pip still gets to the park, which was the need. Borrowing a coat means the budget can stay in the jar. Sharing can cover a need without spending.",
          },
          {
            id: "cap",
            label: "Buy the shiny cap",
            detail: "A want from the stall. It costs 14 game coins.",
            coinDelta: -14,
            bonusCoins: 0,
            tag: "want",
            meetsNeed: false,
            feedbackTitle: "The cap is a want",
            feedbackBody:
              "The cap looks great, and it does not get Pip to the park. Those 14 game coins are the opportunity cost: they are gone for the fare, water, or saving.",
          },
        ],
      },
      {
        id: "water",
        title: "At the park",
        prompt: "Pip has been outside. There is a water cart, a sticker stall, or the choice to keep the rest.",
        income: 0,
        incomeLabel: "",
        choices: [
          {
            id: "water",
            label: "Buy a bottle of water",
            detail: "A need when you are thirsty. It costs 3 game coins.",
            coinDelta: -3,
            bonusCoins: 0,
            tag: "need",
            meetsNeed: true,
            feedbackTitle: "Water is a need",
            feedbackBody:
              "Thirst is a body need. 3 game coins is a small part of the budget, and Pip can keep playing.",
          },
          {
            id: "stickers",
            label: "Buy a sticker pack",
            detail: "A want. It costs 10 game coins.",
            coinDelta: -10,
            bonusCoins: 0,
            tag: "want",
            meetsNeed: false,
            feedbackTitle: "Stickers are a want",
            feedbackBody:
              "Stickers are fun to collect. They are a want. If the budget is already small, this choice can leave a thirst need unmet. That trade-off is the lesson.",
          },
          {
            id: "save-rest",
            label: "Keep the remaining coins",
            detail: "Save what is left for another day.",
            coinDelta: 0,
            bonusCoins: 0,
            tag: "save",
            meetsNeed: false,
            feedbackTitle: "Saving is a plan",
            feedbackBody:
              "Keeping coins is saving. Water would have been a need, so check that thirst is already handled. Saving what you do not need yet makes a later goal easier.",
          },
        ],
      },
    ],
    supplies: [],
    prices: [],
    lemonadeIntro: "",
    quiz: [
      {
        id: "need-check",
        prompt: "Which one is a need?",
        choices: [
          {
            id: "water",
            label: "Water when you are thirsty",
            correct: true,
            explanation: "Water helps your body. That is a need. Stickers and extra sweets are wants.",
          },
          {
            id: "stickers",
            label: "A third sticker pack",
            correct: false,
            explanation: "Stickers are fun, so they are a want. A need is something that helps you stay healthy, safe, or ready to learn.",
          },
          {
            id: "cap",
            label: "A shiny cap you like",
            correct: false,
            explanation: "A cap you want for style is a want. Wants can be enjoyable. They are just not the same as needs.",
          },
        ],
      },
      {
        id: "opportunity",
        prompt: "What is opportunity cost?",
        choices: [
          {
            id: "tradeoff",
            label: "What you give up when you choose one thing",
            correct: true,
            explanation: "If coins buy cookies, those coins cannot also buy the bus fare. That given-up choice is the opportunity cost.",
          },
          {
            id: "free",
            label: "Coins that appear from nowhere",
            correct: false,
            explanation: "Coins do not appear from nowhere in this game. Opportunity cost is the next best thing you did not choose.",
          },
        ],
      },
    ],
    rewards: {
      xp: 40,
      coins: 12,
      badgeId: "need-spotter",
      badgeName: "Need Spotter",
      badgeDescription: "You practiced needs, wants, and trade-offs on market day.",
    },
  },
  {
    id: "savings-quest",
    slug: "savings-quest",
    title: "Savings Quest",
    summary: "Start with 100 game coins and save toward a 150-coin bicycle.",
    story:
      "Pip wants a bicycle that costs 150 fictional game coins. The practice jar already holds 100. Each week Pip receives 20 game coins of helper pay. That pay is income. If Pip leaves the jar untouched for the week, the town bank adds 3 game coins. That small extra is this game's example of simple interest.",
    learningGoal: "Use income, a savings goal, and a simple-interest example to reach 150 game coins.",
    ageMin: 8,
    ageMax: 12,
    difficulty: "medium",
    topic: "Saving",
    order: 2,
    engine: "choices",
    startingCoins: 100,
    goalAmount: 150,
    needsRequired: 0,
    successHeadline: "The practice jar reached the bicycle.",
    practiceHeadline: "The bicycle is still ahead, and you can see why.",
    steps: [
      {
        id: "week-1",
        title: "Week 1",
        prompt: "Helper pay arrives. Then a friend invites Pip to the arcade, and school pencils are running low.",
        income: 20,
        incomeLabel: "Helper pay, which is income",
        choices: [
          {
            id: "save",
            label: "Leave the jar untouched",
            detail: "The bank adds 3 game coins of simple interest.",
            coinDelta: 0,
            bonusCoins: 3,
            tag: "save",
            meetsNeed: false,
            feedbackTitle: "The jar earned simple interest",
            feedbackBody:
              "You kept the coins saved, so the town bank added 3 game coins. In this game, that extra is simple interest: a small bonus for leaving savings put. Real investing can also lose money. These coins are pretend.",
          },
          {
            id: "arcade",
            label: "Spend the afternoon at the arcade",
            detail: "A want. It costs 30 game coins.",
            coinDelta: -30,
            bonusCoins: 0,
            tag: "want",
            meetsNeed: false,
            feedbackTitle: "The arcade is a want",
            feedbackBody:
              "Arcade time is fun, and it is a want. 30 game coins left the bicycle jar. The opportunity cost is a slower path to 150. The bank only adds interest when the jar stays untouched.",
          },
          {
            id: "pencils",
            label: "Buy school pencils",
            detail: "A need for learning. They cost 6 game coins.",
            coinDelta: -6,
            bonusCoins: 0,
            tag: "need",
            meetsNeed: true,
            feedbackTitle: "Pencils are a need",
            feedbackBody:
              "Pencils help Pip do schoolwork, so this is a need. A need can fit inside a savings plan. The jar did not earn interest this week because coins were taken out.",
          },
        ],
      },
      {
        id: "week-2",
        title: "Week 2",
        prompt: "Another 20 game coins of income arrive. Rain is coming, and a comic is on sale.",
        income: 20,
        incomeLabel: "Helper pay, which is income",
        choices: [
          {
            id: "save",
            label: "Leave the jar untouched",
            detail: "Earn 3 game coins of simple interest.",
            coinDelta: 0,
            bonusCoins: 3,
            tag: "save",
            meetsNeed: false,
            feedbackTitle: "Interest needs the coins to stay",
            feedbackBody:
              "Simple interest in this mission is 3 game coins for a week the jar is not used. It is a teaching example with fictional coins, not a promise about real banks.",
          },
          {
            id: "comic",
            label: "Buy the new comic",
            detail: "A want. It costs 25 game coins.",
            coinDelta: -25,
            bonusCoins: 0,
            tag: "want",
            meetsNeed: false,
            feedbackTitle: "The comic is a want",
            feedbackBody:
              "Stories are fun. This comic is a want, so 25 game coins are no longer saved. You can still reach the bicycle if other weeks stay quieter.",
          },
          {
            id: "boots",
            label: "Buy rain boots",
            detail: "A need for wet walks to school. They cost 14 game coins.",
            coinDelta: -14,
            bonusCoins: 0,
            tag: "need",
            meetsNeed: true,
            feedbackTitle: "Boots cover a need",
            feedbackBody:
              "Dry feet on the walk to school are a need. 14 game coins is a real cost, and the goal can still work if other weeks are saved.",
          },
        ],
      },
      {
        id: "week-3",
        title: "Week 3",
        prompt: "Income arrives again. A snack cart and a friend's birthday are both today.",
        income: 20,
        incomeLabel: "Helper pay, which is income",
        choices: [
          {
            id: "save",
            label: "Leave the jar untouched",
            detail: "Earn 3 game coins of simple interest.",
            coinDelta: 0,
            bonusCoins: 3,
            tag: "save",
            meetsNeed: false,
            feedbackTitle: "The goal gets closer",
            feedbackBody:
              "Unspent coins stay aimed at the bicycle, and the bank adds 3. A budget is a plan: income in, a choice, then a look at what is left.",
          },
          {
            id: "snack",
            label: "Buy the fancy snack",
            detail: "A want. It costs 20 game coins.",
            coinDelta: -20,
            bonusCoins: 0,
            tag: "want",
            meetsNeed: false,
            feedbackTitle: "The snack is a want",
            feedbackBody:
              "A fancy snack is a want. It uses a whole week of income. That is okay to see in practice. The bicycle total moves more slowly.",
          },
          {
            id: "gift",
            label: "Bring a small birthday gift",
            detail: "A kind spend. It costs 7 game coins.",
            coinDelta: -7,
            bonusCoins: 0,
            tag: "spend",
            meetsNeed: false,
            feedbackTitle: "A gift is still a spend",
            feedbackBody:
              "A gift can matter to a friend. It still leaves the jar, so those 7 game coins are not part of the bicycle yet. Kind and costly can both be true.",
          },
        ],
      },
      {
        id: "week-4",
        title: "Week 4",
        prompt: "Last week of the quest. Income arrives. The bicycle costs 150 game coins.",
        income: 20,
        incomeLabel: "Helper pay, which is income",
        choices: [
          {
            id: "save",
            label: "Leave the jar untouched",
            detail: "Earn 3 game coins of simple interest.",
            coinDelta: 0,
            bonusCoins: 3,
            tag: "save",
            meetsNeed: false,
            feedbackTitle: "The jar stayed on the goal",
            feedbackBody:
              "The last week stayed saved, so interest is added again. Compare the ending jar with 150. If it is there, the goal is met. If not, the recap shows the gap.",
          },
          {
            id: "toy",
            label: "Buy the wind-up toy",
            detail: "A want. It costs 30 game coins.",
            coinDelta: -30,
            bonusCoins: 0,
            tag: "want",
            meetsNeed: false,
            feedbackTitle: "The toy is a want",
            feedbackBody:
              "The toy is fun and it is a want. 30 game coins come out at the end, when the goal is closest. Seeing that gap is the lesson, and replay is always open.",
          },
        ],
      },
    ],
    supplies: [],
    prices: [],
    lemonadeIntro: "",
    quiz: [
      {
        id: "interest",
        prompt: "Why did the jar sometimes gain 3 extra game coins?",
        choices: [
          {
            id: "interest",
            label: "Simple interest: a small bonus for leaving savings untouched",
            correct: true,
            explanation:
              "In this mission the bank adds 3 game coins only when you do not take coins out that week. That teaches simple interest with pretend coins.",
          },
          {
            id: "luck",
            label: "A random prize",
            correct: false,
            explanation: "Nothing here is random. The 3 coins are a rule you can count on inside the game.",
          },
        ],
      },
      {
        id: "gap",
        prompt: "The bicycle costs 150 game coins and the jar starts at 100. How many more are needed at the start?",
        choices: [
          {
            id: "fifty",
            label: "50 game coins",
            correct: true,
            explanation: "150 − 100 = 50. Income and interest can help close that gap. Spending opens it again.",
          },
          {
            id: "onefifty",
            label: "150 game coins",
            correct: false,
            explanation: "150 is the full price. Because the jar already has 100, the remaining amount at the start is 50.",
          },
        ],
      },
    ],
    rewards: {
      xp: 40,
      coins: 18,
      badgeId: "goal-getter",
      badgeName: "Goal Getter",
      badgeDescription: "You practiced a 150-coin bicycle goal with income and interest.",
    },
  },
  {
    id: "lemonade-stand",
    slug: "lemonade-stand",
    title: "Lemonade Stand",
    summary: "Choose a price, pay for supplies, and find the profit.",
    story:
      "Pip's stand opens with 30 fictional game coins. First pay for supplies. That cost is an expense. Then pick a price. Customers follow a set rule: a lower price brings more customers, and a higher price brings fewer. Revenue is cups sold times price. Profit = revenue − expenses.",
    learningGoal: "Calculate revenue, expenses, and profit from a price and a supply batch.",
    ageMin: 8,
    ageMax: 12,
    difficulty: "medium",
    topic: "Profit",
    order: 3,
    engine: "lemonade",
    startingCoins: 30,
    goalAmount: null,
    needsRequired: 0,
    successHeadline: "The stand made a profit.",
    practiceHeadline: "The stand finished with a loss, and the formula shows why.",
    steps: [],
    supplies: [
      {
        id: "tiny",
        name: "Tiny table",
        detail: "A small batch. Lower expense, and only 6 cups to sell.",
        cost: 8,
        cups: 6,
      },
      {
        id: "neighborhood",
        name: "Neighborhood stand",
        detail: "A steady batch. 16 game coins buys 14 cups.",
        cost: 16,
        cups: 14,
      },
      {
        id: "block",
        name: "Block party",
        detail: "A big batch. 26 game coins buys 22 cups.",
        cost: 26,
        cups: 22,
      },
      {
        id: "festival",
        name: "Festival cart",
        detail: "40 game coins. Today's purse cannot cover it. This mission does not borrow.",
        cost: 40,
        cups: 30,
      },
    ],
    prices: [
      { price: 1, customers: 20, note: "A bargain. Many kids stop by." },
      { price: 2, customers: 12, note: "A fair sunny-day price." },
      { price: 3, customers: 7, note: "Some kids walk past. Buyers pay more." },
      { price: 4, customers: 3, note: "A fancy price. Only a few say yes." },
    ],
    lemonadeIntro:
      "You cannot spend coins you do not have. Profit can still be negative if expenses are higher than revenue. A loss stays inside this practice stand and does not touch your town wallet.",
    quiz: [
      {
        id: "formula",
        prompt: "Which formula is profit?",
        choices: [
          {
            id: "formula",
            label: "Revenue − expenses",
            correct: true,
            explanation: "Profit = revenue − expenses. Revenue is money from customers. Expenses are the costs you paid.",
          },
          {
            id: "sum",
            label: "Expenses + cups",
            correct: false,
            explanation: "Cups are part of how you find revenue. Profit subtracts expenses from revenue.",
          },
        ],
      },
      {
        id: "revenue",
        prompt: "You sell 4 cups for 3 game coins each. What is the revenue?",
        choices: [
          {
            id: "twelve",
            label: "12 game coins",
            correct: true,
            explanation: "Revenue = 4 × 3 = 12 game coins. Expenses would still be subtracted to find profit.",
          },
          {
            id: "seven",
            label: "7 game coins",
            correct: false,
            explanation: "4 + 3 = 7, but revenue multiplies cups by price. 4 × 3 = 12.",
          },
        ],
      },
    ],
    rewards: {
      xp: 40,
      coins: 16,
      badgeId: "profit-pro",
      badgeName: "Profit Pro",
      badgeDescription: "You priced a stand and practiced revenue, expenses, and profit.",
    },
  },
];
